//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjMiner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8""?><Users><Credential><Account>Alma</Account><Username>cybers01</Username><Password>cfRfHRfR</Password></Credential><Credential><Account>Cecile</Account><Username>cybers02</Username><Password>orrVOnOF</Password></Credential><Credential><Account>Rowen</Account><Username>cybers03</Username><Password>oXTOwycgc</Password></Credential><Credential><Account>Maribel</Account><Username>cybers04</Username><Password>jGfnjVPn</Password></Credential><Credential><Account>Angela</Account><Username>cybers05</Username><Password>bvbvUTUK</Password></Credential></Users>")]
        public string Users {
            get {
                return ((string)(this["Users"]));
            }
            set {
                this["Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Proxy><Server><Name>elite proxy - 1</Name>" +
            "<IPAddress>50.207.44.25</IPAddress><Port>8080</Port></Server><Server><Name>elite" +
            " proxy - 2</Name><IPAddress>104.197.107.186</IPAddress><Port>3128</Port></Server" +
            "></Proxy>")]
        public string ProxyList {
            get {
                return ((string)(this["ProxyList"]));
            }
            set {
                this["ProxyList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test1")]
        public string ProxyName {
            get {
                return ((string)(this["ProxyName"]));
            }
            set {
                this["ProxyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ProxyAddress {
            get {
                return ((string)(this["ProxyAddress"]));
            }
            set {
                this["ProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string ProxyPort {
            get {
                return ((string)(this["ProxyPort"]));
            }
            set {
                this["ProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8""?><Main><Type><Name>Limited</Name><Value>15CECL</Value><Start>04766</Start><End>99999</End></Type><Type><Name>Unlimited</Name><Value>15CECG</Value><Start>02044</Start><End>99999</End></Type><Type><Name>Small Claims</Name><Value>15CESC</Value><Start>01257</Start><End>99999</End></Type></Main>")]
        public string TypeList {
            get {
                return ((string)(this["TypeList"]));
            }
            set {
                this["TypeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
<table  style=""width:100%"">
<tbody>
<tr><td style=""text-align:center""><h3>{0}</he></td></tr>
<tr>
<td  style=""border-style: solid; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">
<tbody>
<tr><td style=""width:50%"">Case Number: {1}</td><td style=""width:50%"">Court: {2}</td></tr>
<tr>
<td>File Date: {3}</td>
<td>Case Type: {4}</td>
</tr>
<tr>
<td colspan=""2"">Case Status: {5}</td>
</tr>
</tbody>
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>

{6}

{11}
{9}


<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%"">
<tbody>
<tr>
<td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">
<tbody>
{7}
</tbody>
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>


<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%"">
<tbody>
<tr>
<td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">
<tbody>
{8}
</tbody>
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>

{10}")]
        public string FresnoHtmlTemplate {
            get {
                return ((string)(this["FresnoHtmlTemplate"]));
            }
            set {
                this["FresnoHtmlTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"body{
font: 12px Arial, sans-serif;
}td{padding: 2px;}

.tyler-bold,.tyler-toggle-controller.open
{
	font-size:14px !important;
	font-weight:bold;
	
}

.tyler-color-muted
{
		font-size:12px;
		margin-left:20px;
}.borderx{padding: 5px; border-bottom: 1px solid  #e0e0e0;}")]
        public string FresnoCss {
            get {
                return ((string)(this["FresnoCss"]));
            }
            set {
                this["FresnoCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;line-height:25px;"">&nbsp;</div>
<table  style=""width:100%"">
<tbody>
<tr>
<td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">
<tbody>
<tr><td  style='width:100%'>
{0}</td>
</tr>
</tbody>
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>")]
        public string tableTemplate {
            get {
                return ((string)(this["tableTemplate"]));
            }
            set {
                this["tableTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;line-height:25px;"">&nbsp;</div>
<table  style=""width:100%"">
<tbody>
<tr>
<td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">

{0}
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>")]
        public string tableTemplate2 {
            get {
                return ((string)(this["tableTemplate2"]));
            }
            set {
                this["tableTemplate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%"">
<tbody>
<tr>
<td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:14px"">
<table style=""font-size:11px;width:100%"">
<tbody>
{0}
</tbody>
</table>
</tr>
</tbody>
</table>
</td>
</tr>

</tbody>
</table>")]
        public string tableTemplate3 {
            get {
                return ((string)(this["tableTemplate3"]));
            }
            set {
                this["tableTemplate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
<table  style=""width:100%;cellspan:0;    border-spacing: 0px; border-collapse: collapse;"">
<tbody>

<tr><td style=""text-align:center;font-size:11px;width:100%"">Nebraska Judicial Branch ­ Case Search</td></tr>
<tr><td style=""text-align:center;font-size:11px;width:100%"">Official Nebraska Government Website</td></tr>
<tr><td style=""font-size:6px;"">&nbsp;</td></tr>
<tr><td style=""text-align:center""><h3><b>Nebraska Supreme Court</b></h3></td></tr>
<tr><td style=""font-size:12px;"">&nbsp;</td></tr>
<tr><td  style=""font-size:12px;border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;border-bottom:0px solid white;padding:8px""><b>Case Summary</b></td></tr>
<tr><td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;font-size:11px;padding:8px"">{0}</td></tr>
</tbody>
</table>


<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%;cellspan:0;    border-spacing: 0px; border-collapse: collapse;"">
<tbody>
<tr><td  style=""font-size:12px;border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;border-bottom:0px solid white;padding:8px""><b>Parties/Attorneys to the Case</b></td></tr>
<tr><td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;font-size:11px;padding:8px"">{1}</td></tr>

</tbody>
</table>

{2}

{3}

{4}

{5}

{6}")]
        public string NebraskaHtmlTemplate {
            get {
                return ((string)(this["NebraskaHtmlTemplate"]));
            }
            set {
                this["NebraskaHtmlTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%;cellspan:0;    border-spacing: 0px; border-collapse: collapse;"">
<tbody>
<tr><td  style=""font-size:12px;border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;border-bottom:0px solid white;padding:8px""><b>{0}</b></td></tr>
<tr><td  style=""border-style: dotted; border-color: #e0e0e0; border-width: 1px;padding:3px;font-size:11px;padding:8px"">{1}</td></tr>

</tbody>
</table>")]
        public string NebraskTableTemplate {
            get {
                return ((string)(this["NebraskTableTemplate"]));
            }
            set {
                this["NebraskTableTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%;cellspan:0;    border-spacing: 0px; border-collapse: collapse;"">
<tbody style=""border:1px solid  #e0e0e0;"">
<tr><td  style=""font-size:12px;border-style: solid; border-color: #e0e0e0; border-width: 1px;padding:3px;padding:8px"" colspan=""4""><b>{0}</b></td></tr>
{1}

</tbody>
</table>")]
        public string NebraskTableTemplate2 {
            get {
                return ((string)(this["NebraskTableTemplate2"]));
            }
            set {
                this["NebraskTableTemplate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""width:100%;font-size:6px;"">&nbsp;</div>
<table  style=""width:100%;cellspan:0;    border-spacing: 0px; border-collapse: collapse;"">
<tbody style=""border:1px solid  #e0e0e0;"">
<tr><td  style=""font-size:12px;border-style: solid; border-color: #e0e0e0; border-width: 1px;padding:3px;padding:8px"" colspan=""5""><b>{0}</b></td></tr>
{1}

</tbody>
</table>")]
        public string NebraskTableTemplate3 {
            get {
                return ((string)(this["NebraskTableTemplate3"]));
            }
            set {
                this["NebraskTableTemplate3"] = value;
            }
        }
    }
}
